version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: task-manager-backend:latest
    container_name: task-manager-backend
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/production.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=24h
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - JWT_REFRESH_EXPIRES_IN=7d
      - UPLOAD_PATH=/app/uploads
      - MAX_FILE_SIZE=10485760
      - LOG_LEVEL=info
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: task-manager-frontend:latest
    container_name: task-manager-frontend
    ports:
      - "8082:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  app-network:
    driver: bridge